// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ae6a2ecc-1c79-4fda-bdb6-b7556a053778",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_aB8dZqATw",
    "aws_user_pools_web_client_id": "1jp94md2325ot76d6hamtbss45"
};


export default awsmobile;
